#!/usr/bin/env python3
import json
import re

# Read the keywords file
with open('extracted_keywords.txt', 'r') as f:
    keywords = [line.strip() for line in f if line.strip()]

# Initialize categories
categories = {
    "Textbooks & Educational Materials": {
        "description": "Knowledge items, textbooks, learning materials",
        "keywords": [],
        "patterns": [
            r'^Textbook',
            r'Language$',
            r'Lore$',
            r'Genealogy',
            r'Parchment',
            r'PoetryStyle',
            r'PoetryTier',
            r'PhrenologyRecipe',
        ]
    },
    "Recipes & Crafting Skills": {
        "description": "Recipes, crafting instructions, craft-related keywords",
        "keywords": [],
        "patterns": [
            r'Recipe$',
            r'Ingredient$',
            r'Related$',
            r'^Crafted$',
            r'^Alchemy$',
            r'^Blacksmithing$',
            r'^Carpentry$',
            r'^CandleMaking$',
            r'^Cooking$',
            r'^Fletching$',
            r'^Leatherworking$',
            r'^Skinning$',
            r'^Tailoring$',
            r'^Whittling$',
            r'^Gardening',
            r'^GardeningRelated',
            r'^Gadgeteering',
            r'^Breeding',
            r'^Mycology',
            r'^Toolcraft',
            r'^Calligraphy',
            r'^FlowerArrangement',
        ]
    },
    "Armor Sets by Type": {
        "description": "Full armor categories by material (Cloth, Leather, Metal, Organic, Wooden)",
        "keywords": [],
        "patterns": [
            r'^ClothArmor$',
            r'^ClothBoots$',
            r'^ClothDyeableArmor$',
            r'^ClothGloves$',
            r'^ClothHelm$',
            r'^ClothPants$',
            r'^ClothShirt$',
            r'^LeatherArmor$',
            r'^LeatherBoots$',
            r'^LeatherDyeableArmor$',
            r'^LeatherGloves$',
            r'^LeatherHelm$',
            r'^LeatherPants$',
            r'^LeatherShirt$',
            r'^MetalArmor$',
            r'^MetalBoots$',
            r'^MetalDyeableArmor$',
            r'^MetalGloves$',
            r'^MetalHelm$',
            r'^MetalPants$',
            r'^MetalShirt$',
            r'^OrganicArmor$',
            r'^OrganicBoots$',
            r'^OrganicDyeableArmor$',
            r'^OrganicGloves$',
            r'^OrganicHelm$',
            r'^OrganicPants$',
            r'^OrganicShirt$',
            r'^WoodenArmor$',
            r'^WoodenBoots$',
            r'^Armor$',
            r'PlateArmor$',
            r'DwarvenPlateArmor$',
            r'OrcishPlateArmor$',
            r'PlateArmor$',
        ]
    },
    "Armor Pieces by Location": {
        "description": "Body-specific armor (boots, gloves, helm, pants, shirt)",
        "keywords": [],
        "skip_patterns": [
            r'^ClothArmor$',
            r'^LeatherArmor$',
            r'^MetalArmor$',
            r'^OrganicArmor$',
            r'^WoodenArmor$',
        ]
    },
    "Melee Weapons": {
        "description": "Swords, daggers, hammers, staffs, hand weapons",
        "keywords": [],
        "patterns": [
            r'^Sword$',
            r'^Dagger$',
            r'^Hammer$',
            r'^Staff$',
            r'^Knife$',
            r'^Club$',
            r'^Dirk$',
            r'^Rapier$',
            r'^Halberd$',
            r'^Trident$',
            r'^Wand$',
            r'^Orb$',
            r'^Axe$',
            r'TuneupKit$',
            r'RecipeForCombatSkill',
            r'MainHand$',
            r'Unarmed',
            r'^FireStaff$',
            r'^IceStaff$',
            r'^WeatherStaff$',
            r'^EnergyBow$',
            r'^Blowpipe$',
            r'^Whip$',
            r'^Pick$',
        ]
    },
    "Ranged Weapons & Projectiles": {
        "description": "Bows, crossbows, arrows, ammunition",
        "keywords": [],
        "patterns": [
            r'^Bow$',
            r'^Crossbow$',
            r'^Arrow',
            r'^BarbedArrow',
            r'^DenseArrow',
            r'^LongArrow',
            r'^ReservoirArrow',
            r'^SnareArrow',
            r'^Arrowhead',
            r'^ArrowShaft',
            r'^BowTuneupKit$',
            r'^AnglingPole$',
            r'Projectile',
        ]
    },
    "Food & Cooking Ingredients": {
        "description": "Fish, meat, vegetables, cooking components",
        "keywords": [],
        "patterns": [
            r'^Fish',
            r'^Meat',
            r'^Fillet',
            r'^Vegetable',
            r'^Fruit$',
            r'^Mushroom',
            r'^Mushroom1$',
            r'^Herb$',
            r'^Plant$',
            r'^Flower$',
            r'^Seed$',
            r'^Seedling$',
            r'^Root$',
            r'^Berry$',
            r'^Nuts$',
            r'^Grain$',
            r'^Wheat$',
            r'^Corn$',
            r'^CornMeal',
            r'^Flour$',
            r'^Egg$',
            r'^Cream$',
            r'^Butter$',
            r'^Milk$',
            r'^Cheese$',
            r'^Lemon$',
            r'^Lime$',
            r'^Orange$',
            r'^Apple$',
            r'^Pear$',
            r'^Peach$',
            r'^Grape$',
            r'^Banana$',
            r'^Melon$',
            r'^Pumpkin$',
            r'^Squash$',
            r'^Carrot$',
            r'^Lettuce$',
            r'^Spinach$',
            r'^Kale$',
            r'^Cabbage$',
            r'^Onion$',
            r'^Garlic$',
            r'^Pepper$',
            r'^Beet$',
            r'^Potato$',
            r'^Kelp$',
            r'^Seaweed$',
            r'^Watercress$',
            r'^Escarole$',
            r'^Greens$',
            r'^Meat$',
            r'^RawMeat',
            r'^RawDeerMeat',
            r'^RawRabbitMeat',
            r'^DeerMeat$',
            r'^RabbitMeat$',
            r'^CowMeat$',
            r'^PigMeat$',
            r'^ChickenMeat$',
            r'^TurkeyMeat$',
            r'^VenisionMeat$',
            r'^Bacon$',
            r'^PorkShoulder$',
            r'^BeastMeat$',
            r'^CorpseFlesh$',
            r'^OgreStomach$',
            r'^DemonMeat$',
            r'^DinosaurMeat$',
            r'^DogMeat$',
            r'^DwarfMeat$',
            r'^ElfMeat$',
            r'^FaeMeat$',
            r'^HumanMeat$',
            r'^OrcMeat$',
            r'^InsectMeat$',
            r'^AnimalHorn$',
            r'^BearClaw$',
            r'^Tongue$',
            r'^Brain$',
            r'^Heart$',
            r'^Kidney$',
            r'^Liver$',
            r'^Lung$',
            r'^Stomach$',
        ]
    },
    "Potions, Drinks & Beverages": {
        "description": "Potions, poisons, drinks, alcohol",
        "keywords": [],
        "patterns": [
            r'^Potion$',
            r'Potion=',
            r'^MaxHealthPotion',
            r'^RestorativePotion',
            r'^Drink$',
            r'Drink=',
            r'^Beer$',
            r'^Wine$',
            r'^Alcohol',
            r'^Ale$',
            r'^Mead$',
            r'^Whiskey$',
            r'^Rum$',
            r'^Vodka$',
            r'^Brandy$',
            r'^Tea$',
            r'^Coffee$',
            r'^Juice$',
            r'^Poison$',
            r'Poison$',
            r'^PoisonBlade',
            r'^PoisonousDrink$',
            r'^PoisonousFood$',
            r'^Decoction$',
            r'^Tincture$',
            r'^Serum$',
            r'^Elixir$',
            r'^SkillBoostPotion$',
            r'^ResistancePotion$',
            r'^HardLiquor',
            r'^Draught$',
            r'^Brew$',
            r'^Cordial$',
            r'^Liqueur$',
            r'^Punch$',
            r'^Cider$',
            r'^MreadyToEat$',
            r'^BeerKeg',
            r'^AlcoholBarrel',
            r'^HardLiquorBarrel',
            r'^WineBottle',
            r'^BottledItem',
            r'^Oil$',
            r'Oil$',
        ]
    },
    "Jewelry & Adornments": {
        "description": "Amulets, rings, necklaces, decorative items",
        "keywords": [],
        "patterns": [
            r'^Amulet',
            r'^Ring$',
            r'^Necklace$',
            r'^Bracelet$',
            r'^Anklet$',
            r'^Pendant$',
            r'^Brooch$',
            r'^Earring$',
            r'^Tiara$',
            r'^Crown$',
            r'^Circlet$',
            r'^Torque$',
            r'^Torc$',
            r'Ring$',
            r'Jewelry$',
            r'RacialJewelry',
            r'DwarvenJewelry',
            r'ElvishJewelry',
        ]
    },
    "Crafting Materials & Gems": {
        "description": "Ores, crystals, gems, cloth, raw components",
        "keywords": [],
        "patterns": [
            r'^Gem$',
            r'Gem=',
            r'^Agate',
            r'^Amethyst',
            r'^Aquamarine',
            r'^Azurite',
            r'^Bloodstone',
            r'^BlueSpinel',
            r'^Carnelian',
            r'^Chrysoberyl',
            r'^Citrine',
            r'^Diamond',
            r'^Danburite',
            r'^Emerald',
            r'^Fluorite',
            r'^Garnet',
            r'^Goshenite',
            r'^LapisLazuli',
            r'^Malachite',
            r'^Moonstone',
            r'^Morganite',
            r'^MossAgate',
            r'^Obsidian',
            r'^Onyx',
            r'^Opal',
            r'^Peridot',
            r'^Quartz',
            r'^Ruby',
            r'^Sapphire',
            r'^Sardonyx',
            r'^Serpentine',
            r'^Sunstone',
            r'^TigersEye',
            r'^Topaz',
            r'^Tourmaline',
            r'^Tsavorite',
            r'^Turquoise',
            r'^Massive',
            r'^Cinnabar',
            r'^Stibnite',
            r'^Molybdenum',
            r'^Iridium',
            r'^Xedrite',
            r'^Xogrite',
            r'^Vervadium',
            r'^Ore$',
            r'^Iron$',
            r'^Steel$',
            r'^Copper',
            r'^Silver',
            r'^Gold',
            r'^Brass',
            r'^Bronze',
            r'^Platinum',
            r'^Lead',
            r'^Tin',
            r'^Zinc',
            r'^Mercury$',
            r'^Sulfur$',
            r'^Salt',
            r'^Dye$',
            r'^DyePot',
            r'^Resin$',
            r'^Lacquer$',
            r'^Varnish$',
            r'^Polish$',
            r'^Wax$',
            r'^Ash$',
            r'^Coal$',
            r'^Sand$',
            r'^Clay$',
            r'^Dirt$',
            r'^Soil$',
            r'^Mud$',
            r'^Stone$',
            r'^Rock$',
            r'^Pebble$',
            r'^Glass$',
            r'^Crystal$',
            r'^Silk$',
            r'^SpiderSilk',
            r'^Cloth$',
            r'^Linen$',
            r'^Cotton$',
            r'^Wool$',
            r'^Leather',
            r'^LeatherRoll',
            r'^LeatherStrips$',
            r'^Rawhide$',
            r'^Hide$',
            r'^Skin$',
            r'^Flawless',
            r'^Carapace$',
            r'^Shell$',
            r'^Bone$',
            r'^BoneHook',
            r'^Horn$',
            r'^Tooth$',
            r'^Tusk$',
            r'^Fang$',
            r'^Scale$',
            r'^Feather$',
            r'^Hair$',
            r'^Fur$',
            r'^TuftOfFur$',
            r'^Wood$',
            r'^Log$',
            r'^Timber$',
            r'^Plank$',
            r'^CedarWood',
            r'^MapleWood',
            r'^OakWood',
            r'^SpruceWood',
            r'^TreewoodWood',
            r'^MetalSlab',
            r'^Ingot$',
            r'^Nugget$',
            r'^Dust$',
            r'^Powder$',
            r'^Fragment$',
            r'^Shard$',
            r'^Scrap$',
            r'^Slag$',
            r'^Slag$',
            r'^Inkwell$',
            r'^Ink$',
            r'^BasicInk$',
            r'^AdvancedInk$',
            r'^AmazingInk$',
            r'^AstoundingInk$',
            r'^BreathtakingInk$',
            r'^CausticInk',
            r'^IncredibleInk$',
            r'^ExpertInk$',
            r'^HolisticInk',
            r'^VolatileInk',
            r'^Filament$',
            r'^Thread$',
            r'^String$',
            r'^Cord$',
            r'^Rope$',
            r'^TubeWood$',
        ]
    },
    "Books, Scrolls & Documents": {
        "description": "Books, documents, scrolls, writing",
        "keywords": [],
        "patterns": [
            r'^Book$',
            r'Book=',
            r'^AncientBook',
            r'^Scroll$',
            r'^Document$',
            r'Document=',
            r'^Parchment',
            r'^LetterOfAuthority$',
            r'^LetterToYetta',
            r'^TitleScroll$',
            r'^LetterOfUnlock',
            r'^WritOfUnlock',
            r'^GoldenWritOfUnlock',
            r'^WritingRelated$',
        ]
    },
    "Furniture & Containers": {
        "description": "Chests, chairs, benches, household items",
        "keywords": [],
        "patterns": [
            r'^Chest$',
            r'^ChestAugment$',
            r'^Barrel$',
            r'^StorageCrate',
            r'^TrashCan$',
            r'^Bed$',
            r'^Chair$',
            r'^Bench$',
            r'^Table$',
            r'^Desk$',
            r'^Cabinet$',
            r'^Shelf$',
            r'^Wardrobe$',
            r'^Dresser$',
            r'^Stool$',
            r'^MeditationStool$',
            r'^Crate$',
            r'^Container$',
            r'^Urn$',
            r'^Vase$',
            r'^Pot$',
            r'^Pan$',
            r'^Kettle$',
            r'^Cauldron$',
            r'^Teapot$',
            r'^Cup$',
            r'^Plate$',
            r'^Bowl$',
            r'^Dish$',
            r'^Goblet$',
            r'^Flask$',
            r'^Bottle$',
            r'^EmptyBottle$',
            r'^Bucket$',
            r'^EmptyBucket$',
            r'^Well$',
            r'^Fountain$',
            r'^Hearth$',
            r'^Campfire$',
            r'^Fireplace$',
            r'^Lamp$',
            r'^Lantern$',
            r'^Candle$',
            r'^Torch$',
            r'^Wick$',
            r'^Sconce$',
            r'^Chandelier$',
            r'^Mirror$',
            r'^Painting$',
            r'^Artwork$',
            r'^Banner$',
            r'^Tapestry$',
            r'^Rug$',
            r'^Carpet$',
            r'^Mat$',
            r'^Cushion$',
            r'^Pillow$',
            r'^Blanket$',
            r'^Curtain$',
            r'^Drape$',
            r'^Shutter$',
            r'^Door$',
            r'^Gate$',
            r'^Fence$',
            r'^Wall$',
            r'^Floor$',
            r'^Ceiling$',
            r'^Roof$',
        ]
    },
    "Tools & Specialized Equipment": {
        "description": "First aid kits, chemistry equipment, tools",
        "keywords": [],
        "patterns": [
            r'^FirstAidKit',
            r'^FirstAidBomb',
            r'^FirstAidGarnet',
            r'^ChemistryEquipment$',
            r'^ChemistryBeaker$',
            r'^ChemistryFlask$',
            r'^Hammer$',
            r'^Axe$',
            r'^Saw$',
            r'^Shovel$',
            r'^StandardShovel$',
            r'^Pick$',
            r'^Pickaxe$',
            r'^Hoe$',
            r'^Rake$',
            r'^Broom$',
            r'^Brush$',
            r'^Brush$',
            r'^Needle$',
            r'^Pin$',
            r'^Tack$',
            r'^Nail$',
            r'^Rivet$',
            r'^Screw$',
            r'^Bolt$',
            r'^Hinge$',
            r'^Lock$',
            r'^Key$',
            r'^Lockpick',
            r'^Wrench$',
            r'^Pliers$',
            r'^Tongs$',
            r'^Forceps$',
            r'^Knife$',
            r'^Blade$',
            r'^Sword$',
            r'^SkinningKnife',
            r'^ButcherKnife',
            r'^OysterKnife',
            r'^Compass$',
            r'^Map$',
            r'^Chart$',
            r'^Scale$',
            r'^Balance$',
            r'^Weight$',
            r'^Measure$',
            r'^Ruler$',
            r'^Sextant$',
            r'^Telescope$',
            r'^Magnifier$',
            r'^Loupe$',
            r'^Eyeglass$',
            r'^Mirror$',
            r'^Lens$',
            r'^Prism$',
            r'^Flashlight$',
            r'^Lantern$',
            r'^Torch$',
            r'^Candle$',
            r'^Lamp$',
            r'^Wick$',
            r'^Oil$',
            r'^Fuel$',
            r'^Rope$',
            r'^Cord$',
            r'^Chain$',
            r'^Hook$',
            r'^Pulley$',
            r'^Lever$',
            r'^Crank$',
            r'^Wheel$',
            r'^Gear$',
            r'^Valve$',
            r'^Pipe$',
            r'^TubeWood$',
            r'^Vise$',
            r'^Clamp$',
            r'^Vice$',
            r'^Press$',
            r'^Anvil$',
            r'^Furnace$',
            r'^Kiln$',
            r'^Oven$',
            r'^Stove$',
            r'^Range$',
            r'^Mortar$',
            r'^Pestle$',
            r'^Grinder$',
            r'^Mill$',
            r'^Wheel$',
            r'^Bellows$',
            r'^Tongs$',
            r'^Crucible$',
            r'^Retort$',
            r'^Alembic$',
            r'^Condenser$',
            r'^Distiller$',
            r'^Fermenter$',
            r'^Barrel$',
            r'^Keg$',
            r'^Tank$',
            r'^Vat$',
            r'Equipment$',
            r'^CraniometerMain',
            r'^ArmorPatchKit',
            r'^BowTuneupKit',
            r'^ClawTuneupKit$',
            r'^DaggerTuneupKit$',
            r'^ReweightingKit$',
            r'^JewelersMaintenanceKit$',
            r'^TuneupKit$',
            r'^ConsumableKit$',
        ]
    },
    "Wearable Gear & Accessories": {
        "description": "Belts, clothing, saddles, personal gear",
        "keywords": [],
        "patterns": [
            r'^Belt$',
            r'^Saddle$',
            r'^Saddlebag',
            r'^SaddleBlanket',
            r'^Reins$',
            r'^Horseshoes$',
            r'^Blanket$',
            r'^Clothing$',
            r'^Clothes$',
            r'^Underwear$',
            r'^Hat$',
            r'^Cap$',
            r'^Hood$',
            r'^Helm$',
            r'^Helmet$',
            r'^Headband$',
            r'^Crown$',
            r'^Tiara$',
            r'^Circlet$',
            r'^Turban$',
            r'^Bonnet$',
            r'^Beret$',
            r'^Scarf$',
            r'^Cloak$',
            r'^Cape$',
            r'^Robe$',
            r'^Dress$',
            r'^Gown$',
            r'^Coat$',
            r'^Jacket$',
            r'^Shirt$',
            r'^Blouse$',
            r'^Tunic$',
            r'^Vest$',
            r'^Waistcoat$',
            r'^Pants$',
            r'^Trousers$',
            r'^Breeches$',
            r'^Shorts$',
            r'^Skirt$',
            r'^Kilt$',
            r'^Leggings$',
            r'^Stockings$',
            r'^Socks$',
            r'^Slippers$',
            r'^Shoes$',
            r'^Boots$',
            r'^Sandals$',
            r'^Gloves$',
            r'^Mittens$',
            r'^Gauntlets$',
            r'^Vambraces$',
            r'^Bracers$',
            r'^Armguards$',
            r'^Legguards$',
            r'^Shin$',
            r'^Greaves$',
            r'^Chausses$',
            r'^Gorget$',
            r'^Pauldrons$',
            r'^Shoulders$',
            r'^Spaulders$',
            r'^Breastplate$',
            r'^Cuirass$',
            r'^Backplate$',
            r'^Faulds$',
            r'^Tassets$',
            r'^Waist$',
            r'^Feet$',
            r'^Hands$',
            r'^Head$',
            r'^Legs$',
            r'^Arms$',
            r'^Chest$',
            r'^Belly$',
            r'^Back$',
            r'^Shoulder$',
            r'^Elbow$',
            r'^Knee$',
            r'^Ankle$',
            r'^Wrist$',
            r'^Neck$',
            r'^Torso$',
            r'Augment$',
            r'^Harness$',
            r'^YokeString$',
            r'^MountCosmetic',
            r'^MountGlamour',
        ]
    },
    "Treasure, Loot & Quest Items": {
        "description": "MacGuffins, maps, trophies, valuables",
        "keywords": [],
        "patterns": [
            r'^MacGuffin',
            r'^TreasureMap$',
            r'^TreasureClues',
            r'^TrophyCat',
            r'^TrophyKuvou',
            r'^TrophyCerberus',
            r'^Trophy$',
            r'^CorpseTrophy$',
            r'^IvoryTrophy$',
            r'^Token$',
            r'^Rune$',
            r'^Amulet$',
            r'^Talisman$',
            r'^Charm$',
            r'^Fetish',
            r'^MemoryInhibitor$',
            r'^Memory$',
            r'^Soul$',
            r'^Spirit$',
            r'^Ghost$',
            r'^Phantom$',
            r'^Ectoplasm$',
            r'^Wraith$',
            r'^Spectre$',
            r'^Vision$',
            r'^Apparition$',
            r'^Figment$',
            r'^Illusion$',
            r'^Mirage$',
            r'^Hallucination$',
            r'^Dream$',
            r'^Nightmare$',
            r'^Premonition$',
            r'^Omen$',
            r'^Sign$',
            r'^Portent$',
            r'^Prophecy$',
            r'^Oracle$',
            r'^Divination$',
            r'^Relic$',
            r'^Artifact$',
            r'^Heirloom$',
            r'^Keepsake$',
            r'^Memento$',
            r'^Souvenir$',
            r'^Curio$',
            r'^Curiosity$',
            r'^Oddity$',
            r'^Rarity$',
            r'^Treasure$',
            r'^Riches$',
            r'^Wealth$',
            r'^Fortune$',
            r'^Booty$',
            r'^Prize$',
            r'^Reward$',
            r'^Bounty$',
            r'^Spoil$',
            r'^Plunder$',
            r'^Loot$',
            r'^Cache$',
            r'^Stash$',
            r'^Hoard$',
            r'^Vault$',
            r'^Chest$',
            r'^Crate$',
            r'^Urn$',
            r'^Casket$',
            r'^Coffin$',
            r'^Tomb$',
            r'^Grave$',
            r'^Burial$',
            r'^Sepulcher$',
            r'^Mausoleum$',
            r'^Monument$',
            r'^MotherlodeMap$',
            r'^RuinedMap$',
            r'^IlmariWarCacheMap$',
            r'^EventLootKey$',
        ]
    },
    "Currency & Trade Items": {
        "description": "Money, coins, trade goods",
        "keywords": [],
        "patterns": [
            r'^Coin$',
            r'Coin=',
            r'^Money$',
            r'^Cash$',
            r'^Currency$',
            r'^Credit$',
            r'^Badge$',
            r'^Medal$',
            r'^Token$',
            r'^Coupon$',
            r'^Voucher$',
            r'^IOU$',
            r'^PromissoryNote$',
            r'^Bill$',
            r'^Check$',
            r'^Deed$',
            r'^Bond$',
            r'^Stock$',
            r'^Share$',
            r'^Merchandise$',
            r'^Goods$',
            r'^Wares$',
            r'^Commodity$',
            r'^Trade$',
            r'^TradingPost$',
            r'^TradeIn$',
            r'^Barter$',
            r'^Exchange$',
            r'^PovusTradeIn',
            r'^WarBond$',
            r'^CounsilCertificate$',
            r'^Chip$',
        ]
    },
    "Shields & Protective Gear": {
        "description": "Shields and shield-like items",
        "keywords": [],
        "patterns": [
            r'^Shield$',
            r'^MetalShield$',
            r'Shield$',
            r'^OffHandShield$',
            r'^Buckler$',
            r'^Kite$',
            r'^Tower$',
            r'^Heater$',
            r'^Pavise$',
            r'^Aegis$',
            r'^Defense$',
            r'^Protection$',
            r'OrShield$',
        ]
    },
    "Racial & Cultural Items": {
        "description": "Race-specific equipment, cultural artifacts",
        "keywords": [],
        "patterns": [
            r'^BardArmor$',
            r'^BardHorn$',
            r'^BardInstrument$',
            r'^BardLute$',
            r'^WerewolfArmor$',
            r'^OrcishPlateArmor$',
            r'^OrcishCulture',
            r'^OrcishLanguage$',
            r'^OrcishFlour$',
            r'^OrcishWheat$',
            r'^OrcHairComb$',
            r'^OrcArrow',
            r'^GoblinArmor$',
            r'^GoblinCallingCard$',
            r'^GoblinHairpin$',
            r'^GoblinOrangeDye$',
            r'^GoblinSkull$',
            r'^GoblinTrash$',
            r'^HobgoblinArmor$',
            r'^DwarvenJewelry',
            r'^DwarvenPlateArmor$',
            r'^ElvishJewelry',
            r'^ElvishStyle$',
            r'^FaeMetalArmor$',
            r'^FaeSilk$',
            r'^FaeMeat$',
            r'^FaeFelt$',
            r'^FaeNavy$',
            r'^RatkinAparatif$',
            r'^RatkinDigestif$',
            r'^RatkinNecroTalisman$',
            r'^SummerCourtArmor$',
            r'^WinterCourtArmor$',
            r'^EltibuleArmor$',
            r'^FaeMetalArmor$',
            r'^NonFaeMetalArmor$',
            r'^RiShinPriestGarment$',
            r'^RanalonCulture',
            r'^RanalonGlassBracelet$',
            r'^SirineCheese$',
            r'^SirinesBelt$',
            r'Racial$',
            r'Culture$',
        ]
    },
    "System Tags & Metadata": {
        "description": "Internal tags, lint warnings, system annotations",
        "keywords": [],
        "patterns": [
            r'^Lint_',
            r'^AutoCleanUp$',
            r'^NoWorkOrders$',
            r'^NoPlayerShops$',
            r'^Temporary$',
            r'^IngredientOnly$',
            r'^NotDyeable$',
            r'^Indestructible$',
            r'^UnsafeToTransport$',
            r'^UnwearableWhileMounted$',
            r'^NoGlamour$',
            r'^NoGourmandBonus$',
            r'^SaddlebagAccess$',
            r'^Sittable$',
            r'^Backplate$',
            r'^EmptyHand$',
            r'^Temporary$',
            r'^Maximize$',
            r'^Dissolvable$',
            r'^Meltable',
            r'^MeltOnGround',
            r'^Millable$',
            r'^Dissolving$',
            r'^Sharpen$',
            r'^SharpenableWeapon$',
            r'^Consumable$',
            r'^Edible$',
            r'^GenericTSysMunge$',
            r'^RequestBreedinPet',
            r'^Require',
            r'^UseInStable_',
            r'^BackerDesigned$',
        ]
    },
}

# Process keywords
uncategorized = []

for keyword in keywords:
    categorized = False
    
    for category_name, category_data in categories.items():
        if 'skip_patterns' in category_data:
            if any(re.match(pattern, keyword) for pattern in category_data['skip_patterns']):
                continue
        
        if 'patterns' in category_data:
            if any(re.match(pattern, keyword) for pattern in category_data['patterns']):
                category_data['keywords'].append(keyword)
                categorized = True
                break
    
    if not categorized:
        uncategorized.append(keyword)

# Second pass: Smart categorization for uncategorized keywords
for keyword in uncategorized[:]:
    categorized = False
    
    # Armor pieces by location (body parts)
    if any(x in keyword.lower() for x in ['boots', 'gloves', 'helm', 'pants', 'shirt', 'feet', 'hands', 'head', 'legs', 'arms', 'chest', 'waist', 'shoulder', 'augment']):
        if not any(x in keyword for x in ['ClothArmor', 'LeatherArmor', 'MetalArmor', 'OrganicArmor', 'WoodenArmor']):
            categories["Armor Pieces by Location"]["keywords"].append(keyword)
            categorized = True
    
    # Weapons (melee)
    if not categorized and any(x in keyword.lower() for x in ['sword', 'dagger', 'hammer', 'staff', 'knife', 'club', 'dirk', 'rapier', 'halberd', 'trident', 'wand', 'orb', 'axe']):
        categories["Melee Weapons"]["keywords"].append(keyword)
        categorized = True
    
    # Food & Cooking
    if not categorized and any(x in keyword.lower() for x in ['dish=', 'fish', 'meat', 'vegetable', 'fruit', 'mushroom', 'herb', 'plant', 'flower', 'seed', 'egg', 'cheese', 'bread', 'cake', 'cookie', 'pie', 'soup', 'stew', 'broth', 'sauce', 'dressing', 'tofu']):
        categories["Food & Cooking Ingredients"]["keywords"].append(keyword)
        categorized = True
    
    # Potions & Drinks
    if not categorized and any(x in keyword.lower() for x in ['potion', 'drink', 'beer', 'wine', 'ale', 'spirit', 'liquor', 'poison', 'tincture', 'elixir']):
        categories["Potions, Drinks & Beverages"]["keywords"].append(keyword)
        categorized = True
    
    # Crafting Materials
    if not categorized and any(x in keyword.lower() for x in ['ore', 'copper', 'silver', 'gold', 'iron', 'steel', 'gem', 'crystal', 'silk', 'cloth', 'leather', 'horn', 'bone', 'scales', 'feather', 'wood', 'ink']):
        categories["Crafting Materials & Gems"]["keywords"].append(keyword)
        categorized = True
    
    # Recipes & Skills
    if not categorized and any(x in keyword.lower() for x in ['recipe', 'ingredient', 'related']):
        categories["Recipes & Crafting Skills"]["keywords"].append(keyword)
        categorized = True
    
    # Default to "Treasure, Loot & Quest Items" for anything remaining
    if not categorized:
        categories["Treasure, Loot & Quest Items"]["keywords"].append(keyword)

# Remove patterns key and sort
final_categories = {}
for category_name in sorted(categories.keys()):
    category = categories[category_name]
    final_categories[category_name] = {
        "description": category["description"],
        "keywords": sorted(list(set(category["keywords"])))
    }

# Generate summary
summary = {
    "total_keywords": len(keywords),
    "total_categories": 19,
    "category_breakdown": {}
}

total_check = 0
for category_name, category_data in final_categories.items():
    count = len(category_data["keywords"])
    summary["category_breakdown"][category_name] = count
    total_check += count

# Create output structure
output = {
    "meta_categories": final_categories,
    "summary": summary
}

# Save to JSON file
with open('keywords_meta_category_mapping.json', 'w', encoding='utf-8') as f:
    json.dump(output, f, indent=2, ensure_ascii=False)

print(f"Categorization complete!")
print(f"Total keywords: {len(keywords)}")
print(f"Total categorized: {total_check}")
print(f"Categories created: {len(final_categories)}")
print("\nCategory breakdown:")
for category, count in sorted(summary["category_breakdown"].items(), key=lambda x: -x[1]):
    print(f"  {category}: {count}")
